### ISSUE TITLE
Move fourier slice interpolation to interpax

### ISSUE THREAD

**Issue by mjo22** [mjo22/cryojax#135]
I recently found this package: https://github.com/f0uriest/interpax/

I think it would be a great idea to make the fourier slice extraction use this. Not yet sure if they have the functionality we need.

@geoffwoollard, I wonder if the fourier slice insertion would also benefit.

**Comment by geoffwoollard** [comment]
I think it's worth finishing the slice insertion PR (perhaps or perhaps not working through jaxifying things over pure numpy).  And then once dust has settled seeing if there is a good fit. That way I'll understand precisely how things are wired up and have something to test it against.

**Comment by geoffwoollard** [comment]
I looked a bit around the documentation of interpax. 

I like the functionality of different interpolation kernels.

However I couldn't find examples.

**Comment by mjo22** [comment]
Closing for now, this would be good but interpax is not mature enough. With #137 I've put off a need for this by making a local copy of map_coordinates, since JAX will be deprecating it.
