### ISSUE TITLE
Create cryojax.experimental submodule 

### ISSUE THREAD

**Issue by mjo22** [mjo22/cryojax#209]
I think we need a way of structuring `cryojax` so that currently untested features are part of a semi-public API. A typical JAX convention would be to create something called `cryojax.experimental`. Things we can add to this are `AbstractDetector` implementations, `AbstractDQE` implementations, `AbstractIce`, and `ElectronDose`. It would be good to then include usage of an `AbstractDistribution` to simulate a noisy image, as this this is the most stable use-case right now.

**Comment by aevans1** [comment]
For reference, what are some existing jax-based libraries you are thinking of for inspiration with the `.experimental` to put the semi-public API?

**Comment by mjo22** [comment]
JAX itself has a `jax.experimental` submodule! Package in the `equinox` ecosystem have something similar called `*.internal`, but I think the idea there is different—`equinox.internal` I don’t think necessarily has intent to become public API. Some things in there I think plan to stay semi-public and are for advanced usages of the library.

**Comment by mjo22** [comment]
Closing for now without doing this, but good to keep this in mind for the future.
