### ISSUE TITLE
Implement integrator that simulates an image from an atom potential directly

### ISSUE THREAD

**Issue by DSilva27** [mjo22/cryojax#224]

**Comment by mjo22** [comment]
In order to do this, we would just have to make a subclass of the `cryojax.simulator.AbstractPotentialIntegrator`, and then we could write something like

```python
from typing_extensions import override
from jaxtyping import Array, Complex
from cryojax.image import rfftn

class GaussianMixtureProjection(AbstractPotentialIntegrator[GaussianMixtureAtomicPotential], strict=True):

    def __init__(...):
        # Initialize any parameters for the algorithm we want to be able to tune

    @override
    def compute_fourier_integrated_potential(potential: GaussianMixtureAtomicPotential, instrument_config: InstrumentConfig) -> Complex[Array, '{instrument_config.padded_y_dim} {instrument_config.padded_x_dim//2+1}']:
        # Grab information from the `instrument_config` like the `instrument_config.pixel_size` and 
        # `instrument_config.padded_shape` and do some things
        ...
        # Compute the projection in real space, assuming that the `potential` is already at the rotation
        # we want
        projection = ...
        # Go to fourier space in cryojax's conventions
        return rfftn(projection)
```

Then this should work with everything in cryojax!

**Comment by mjo22** [comment]
Maybe the `__init__` should take in a parameter that specifies how much to upsample the image? Then we can do fourier cropping before returning the image

**Comment by DSilva27** [comment]
> We should analytically work out the projection integral, starting with the expression in the docs for PengAtomicPotential.as_real_voxel_grid. I think we will pick up some kind of pre-factor from the integration, which will make sure we have things in the right units

It simply changes the b^(3/2) to b

**Comment by mjo22** [comment]
Ah of course that’s right!
