### ISSUE TITLE
Converting to ortho FFT Convention

### ISSUE THREAD

**Issue by ehthiede** [mjo22/cryojax#239]
As per prior discussion between Michael and I, we are considering converting all of the (I)FFT operations to the "ortho" convention.  This will ensure that the power of the image in Fourier space stays consistent regardless of how many pixels we use.

**Comment by mjo22** [comment]
Converted to "ortho" in #241 but having second thoughts. Check out the difference in the code between the two in #242 and let me know what you think.

**Comment by mjo22** [comment]
Closed with #242
