### ISSUE TITLE
Simulating Images directly from Atomic Structures

### ISSUE THREAD

**Issue by ehthiede** [mjo22/cryojax#29]
Currently, we assume that electron densities were provided by the user.  It would be good to incorporate the functionality to go from an atomic structure to an electron density, or alternatively from an atomic structure directly to an image, into the repo.

**Comment by mjo22** [comment]
@ehthiede, a question for you: do you think building a voxel grid will require interacting with the `CTFOptics` object? When I voxelize using cisTEM, I have to specify things like the acceleration voltage and spherical abberation coefficient. If we need these parameters, we don’t want multiple copies of them floating around of course, so we may need a constructor from an `Optics` model.

**Comment by ehthiede** [comment]
I'm desperately trying to remember, but if you are in weak phase object + projection assumption you don't need to bundle these explicitly with the density and they can be incorporated later (e.g. in the CTF).  We should revisit this though.

**Comment by ehthiede** [comment]
I've added the ability to render a 3D electron density (in real space) from a atomic identities and coordinates, and consequently from a pdb.  It makes reasonably heavy use of gemmi as an optional dependency.  It's in #90, and is sort of the bare minimum of what is necessary.

A non-exhaustive list of other features that I think would be good to have working.

- [ ] Integration of PDB loading code into AtomCloud
- [ ] Conversion of an AtomCloud into VoxelClouds
- [ ] Loading of PDBs directly into Fourier Space.
- [ ] Possible speedups by precomputing the Fourier Transform of atomic densities prior to iterating over atoms.
- [ ] Integration of scattering parameters with code that directly constructs images in the plane.
- [ ] Tighter integration with the new stack API

**Comment by mjo22** [comment]
Closing in favor of #177
