### ISSUE TITLE
multislice simulator

### ISSUE THREAD

**Issue by geoffwoollard** [mjo22/cryojax#4]

**Comment by mjo22** [comment]
This package may be great for implementing this: https://github.com/patrick-kidger/diffrax

**Comment by geoffwoollard** [comment]
Some resources on how to implement
https://abtem.github.io/doc/user_guide/walkthrough/multislice.html
https://www.ccp4.ac.uk/ccp4-ed/projects/multislice/
https://hamishgbrown.github.io/py_multislice/pyms/py_multislice.html#pyms.py_multislice.multislice

**Comment by mjo22** [comment]
Some thoughts on implementation:

1. See the function _iterate [here](https://github.com/patrick-kidger/optimistix/blob/main/optimistix/_iterate.py) for some control flow for an iterative solver in JAX, and the function loop [here](https://github.com/patrick-kidger/diffrax/blob/main/diffrax/_integrate.py) for numerical integration control flow. Patrick has implemented a while loop that can be backpropagated in the `equinox.internal` submodule. The while loop in core JAX only supports forward-mode autodiff.
2. I imagine multislice fitting in as an `AbstractPotentialIntegrator`, which takes in an abstract interface for an atomistic representation of a potential (which does not yet exist!). 
3. We will need to generalize the `cryojax` imaging pipeline. Right now, we go from 3D potential -> phase shifts -> squared wavefunction but we will need to support potential -> wavefunction -> squared wavefunction. I expect this generalization will involve work in the `Instrument` and `AbstractSpecimen`, and creating a new `AbstractOptics` model for a complex-exponential CTF. Should be a good opportunity to improve upon the code.

**Comment by geoffwoollard** [comment]
Re 2, I drafted some mulislice code that slices through a discretized potential, and produces the exit wave.

It takes in the potential, slice thickness, and beam wavelength (lambda), and produces the exit wave.

Can you draft something that I can put the core multislice code into?

**Comment by mjo22** [comment]
Starting to implement handling passing an exit wave through the imaging pipeline. 

One issue in this is that the `ImageConfig` needs to store a full frequency plane, rather than the half plane needed for the fourier transform of a real-valued function. For now, we’ve just computed more frequency coordinate systems upon `ImageConfig.__init__`, but this is too cumbersome I think.

Instead, I wonder if all coordinate systems in pixels can be computed at run-time and stored in the `ImageConfig` as properties. I bet XLA will know to compute the meshes only once.

**Comment by geoffwoollard** [comment]
FYI https://abtem.readthedocs.io/en/latest/intro.html follows Eq 6 in Vulović, M., Ravelli, R. B. G., van Vliet, L. J., Koster, A. J., Lazić, I., Lücken, U., … Rieger, B. (2013). Image formation modeling in cryo-electron microscopy. Journal of Structural Biology, 183(1), 19–32. http://doi.org/10.1016/j.jsb.2013.05.008

<img width="462" alt="Screen Shot 2024-04-17 at 11 10 22 PM" src="https://github.com/mjo22/cryojax/assets/4852692/d00bff5f-0399-414c-b866-5f26090ef8bc">

**Comment by mjo22** [comment]
Added an initial commit in the `multislice-updated` branch

**Comment by geoffwoollard** [comment]
Recent TODOs

- [ ] Wave transfer function: functional form
- [ ] Amplitude contrast: bit of an open question. what to do. should agree to projection of one slice in a limit? or do we need separate amp const theory (is mutlislice pure phase)
- [ ] envelope for transfer function. https://github.com/mjo22/cryojax/blob/multislice-updated/src/cryojax/simulator/_transfer_theory/contrast_transfer_theory.py
- [ ] translational phase shifts: can apply to wave, or have to do after ||^2. https://github.com/mjo22/cryojax/blob/multislice-updated/src/cryojax/simulator/_scattering_theory/base_scattering_theory.py#L82
- [ ] tests
  - [ ] one slice should match projection assumption
  - [ ] stacking objects and they are different that projecting
  - [ ] residuals compared to projection is close (including with ctf/wtf) - use imaging pipeline for projection comparison
  - [ ] compare to high energy approx: change scattering theory and transfer function

**Comment by mjo22** [comment]
Translations should be taken care of!

**Comment by mjo22** [comment]
Closing as the first pass of this is merged with #258. New issues are opened in #285 and #286
