### ISSUE TITLE
Incorporate functionality to take projections of simple geometric shapes

### ISSUE THREAD

**Issue by mjo22** [mjo22/cryojax#41]
We want to build in functionality from here: https://github.com/h-alvarenga/simSPI/blob/geometric_micelle/simSPI/geometric_micelle.py

In order to do this, we will need

- [x] 1) New ``ElectronDensity`` and ``ScatteringConfig`` classes
- [x] 2) ``ScatteringConfig.scatter`` should now get a ``Pose`` (need to update ``ImagePipeline._render_specimen()``)
- [x] 3) ``Specimen.realization`` should no longer call ``ElectronDensity.view`` (need to update `scattering configs subclasses (fourierslice...)

We will also need to hook up these functions to the ``cryojax`` attributes, like its coordinate systems and rotation matrices (``Pose.rotation.as_matrix()``).

**Comment by geoffwoollard** [comment]
Notes

* _shape.py in density/
  * have geometric params (and intensity)
  * see https://github.com/mjo22/cryojax/blob/api-update/src/cryojax/simulator/density/_voxels.py#L64
  * won't have a view: view pass
* _analytic.py in scattering/
  * see https://github.com/mjo22/cryojax/blob/api-update/src/cryojax/simulator/scattering/_fourier_slice.py#L50
  * shape projection kernel happening here
  * get pose with: pose.rotation.as_matrix (docs at jax.lie)

* rendering pipeline
  * https://github.com/mjo22/cryojax/blob/api-update/src/cryojax/simulator/image.py#L175
* jax.lax.switch or jax.lax.cond

**Comment by geoffwoollard** [comment]
> 3\. `Specimen.realization` should no longer call `ElectronDensity.view` (need to update `Voxels` and `AtomCloud` to call this instead)

I need help doing this.

**Comment by geoffwoollard** [comment]
TODO:

- [ ] Ensure previous methods aren't buggy (tests pass)
- [ ] Compose micelle with two ellipses and cavity: https://github.com/h-alvarenga/simSPI/blob/geometric_micelle/simSPI/geometric_micelle.py#L148
- [ ] use jax.lax.cond for if statements in projecting rectangle cavity cases: https://github.com/h-alvarenga/simSPI/blob/geometric_micelle/simSPI/geometric_micelle.py#L81C1-L116C53
- [ ] Port over micelle tests: https://github.com/h-alvarenga/simSPI/blob/geometric_micelle/tests/test_geometric_micelle.py

**Comment by mjo22** [comment]
@geoffwoollard question about implementing this: do you assume some kind of smoothness of a density distribution for a particular shape? if shapes are heaviside functions across their boundaries, i think you would get oscillatory artifacts in the fourier transforms. if this is the case, it would probably be good to look further into how to convert this to some kind of phenomenological physical model. maybe there should probably be some kind of b factor parameter

**Comment by geoffwoollard** [comment]
I have thought about this. 

In parallel with this, our group was looking at 3D pseudo atoms of micelles, where coordinates get placed in a region defined by a boundary defined by an ellipsoid equation.

I thought about under what circumstances these models are equivalent
* in the limit of the pseudo atoms getting infinitely small... there is still a b-factor / low pass filter, from the density "kernel" used for each atom (to make it a blob of density).

So yes I do think it makes sense for there to be a b-factor in this sense.

As things stand now, it could go here: https://github.com/mjo22/cryojax/pull/46/files#r1430779862

**Comment by mjo22** [comment]
Update on this: in the current framework I'm not sure this can be accepted. The code currently heavily relies on the assumption that an `ElectronDensity` occupies a particular frame. The newest version of the `Specimen` class make this more explicit. I can't think of a non-hacky way to generalize this right now, but you're welcome to give this a shot...

I think my current philosophy on this is that it would be great to make the pipeline general enough to support this feature. However, I want to be careful about the package increasing in size, particularly with features that aren't published / aren't part of a standard cryo-EM use case. Rather, it would make sense I think to have this as an external package. Examples of things that would be appropriate as external packages are ensemble reweighting, functionality for specific kinds of specimen (e.g micelle and microtubules), etc. Trying my best to adhere to this philosophy myself.

**Comment by geoffwoollard** [comment]
What do you mean by "occupies a particular frame"?

**Comment by mjo22** [comment]
See the `Specimen`

**Comment by mjo22** [comment]
Closing
