### ISSUE TITLE
error with _evaluate_coord_to_grid_sq_distances test-multiatom.ipynb

### ISSUE THREAD

**Issue by aevans1** [mjo22/cryojax#45]
in "api_update" branch:

importing '_evaluate_coord_to_grid_sq_distances' returns:

 ImportError: cannot import name '_evaluate_coord_to_grid_sq_distances' from 'cryojax.simulator.scattering' (/Users/levans/cryo_simulators_inference/cryojax/src/cryojax/simulator/scattering/__init__.py

**Comment by mjo22** [comment]
Thank you for pointing this out, this needs to be changed to

```python
from cryojax.simulator.scattering._gaussian_mixture import _evaluate_coord_to_grid_sq_distances
```
