### ISSUE TITLE
Clean up superfluous FFTs in the pipeline

### ISSUE THREAD

**Issue by mjo22** [mjo22/cryojax#68]
Right now I am a little loose with how many times I transform 2D images back and forth between real and fourier space. Can this be made more efficient? Also, can we make it so we only use the modes on the half plane for 2D and 3D FFTs of real-valued functions (i.e. with `jax.numpy.rfftn` and `jax.numpy.irfftn`)?

**Comment by mjo22** [comment]
This will involve looking at the `extract_slice` function in the fourier slice theorem code, and the `GaussianImage.variance` function. I have ad-hoc things in there to make sure I don’t do redundant computation, but this should just be taken care of when computing wave vectors and FFTs.

Also, the `cryojax.utils.fft` module should instead have conventions for `rfftn` and `irfftn` using `jnp.fft.rfftn` and `jnp.fft.irfftn`.

**Comment by ehthiede** [comment]
Relatedly, we could probably also clean up make_coordinates so it just builds the real-space coords using linspace: this avoids a slightly unclear move to Fourier space and back. and streamlines the code a bit.

**Comment by mjo22** [comment]
Right now, I just use a jnp.fft.fftshift(jnp.fft.fftfreqs(…)) in the _fftfreq1D function instead of a jnp.linspace to be extra sure that real-space coordinate systems match exactly what is expected of an inverse FFT. I may not understand, what do you mean by the move to fourier space?

make_coordinates should not call something called _fftfreqs though… I made _fftfreqs private temporarily to hide this issue.

There is also an annoying detail with jax_finufft, where I have been needing to fftshift in real space after computing the inverse FFT of a projection image. This could probably be fixed though. This is why initially I had my own FFT conventions in cryojax.utils.fft.

**Comment by mjo22** [comment]
On this topic:

XLA turns ``jnp.exp(jnp.log(x))`` -> ``x`` upon jit compilation.

Does it do the same for ``jnp.fft.fftn(jnp.fft.ifftn(x))``? This would make part of this issue a non-issue, as there is some control flow that would not need to be written.

**Comment by mjo22** [comment]
Closing with #105
